#!/usr/bin/env node
'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { BASE_URL, LOCALES, SEO, MESSAGES } = require('../i18n.js');

const ROOT = path.resolve(__dirname, '..');
// Change this only when the published content changes, not on every build.
const CONTENT_MODIFIED = '2026-09-13';
const GENERATED_COMMENT = '<!-- Generated by scripts/build-locales.cjs. Edit templates/index.html and i18n.js. -->';

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (character) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  })[character]);
}

function canonicalUrl(code) {
  return new URL(code === 'en' ? './' : `${code}/`, BASE_URL).href;
}

function relativeLocaleUrl(code, target) {
  if (target === code) return './';
  if (code === 'en') return `${target}/`;
  return target === 'en' ? '../' : `../${target}/`;
}

function translation(code, key) {
  const message = MESSAGES[code]?.[key] ?? MESSAGES.en[key];
  assert.equal(typeof message, 'string', `Missing translation: ${code}.${key}`);
  return message.replace(/\{(\w+)\}/g, (_, parameter) => {
    assert.equal(parameter, 'count', `A static translation requires an explicit value: ${code}.${key}.${parameter}`);
    return '0';
  });
}

function setAttribute(attributes, name, value) {
  const matcher = new RegExp(`(\\s${name}\\s*=\\s*)(["'])(.*?)\\2`, 'i');
  if (matcher.test(attributes)) {
    return attributes.replace(matcher, () => ` ${name}="${escapeHtml(value)}"`);
  }
  return `${attributes} ${name}="${escapeHtml(value)}"`;
}

function setMeta(html, attribute, name, content) {
  const matcher = new RegExp(`<meta\\s+${attribute}="${name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"[^>]*>`, 'g');
  const tag = `<meta ${attribute}="${name}" content="${escapeHtml(content)}">`;
  if (matcher.test(html)) return html.replace(matcher, () => tag);
  return html.replace('</head>', `  ${tag}\n</head>`);
}

function renderPage(template, code) {
  const config = LOCALES[code];
  const seo = SEO[code];
  const url = canonicalUrl(code);
  let html = template.replace(/^<!doctype html>\s*/i, `<!doctype html>\n${GENERATED_COMMENT}\n`);
  html = html.replace(/<html\b([^>]*)>/i, (_, attributes) => {
    attributes = setAttribute(attributes, 'lang', config.tag);
    attributes = setAttribute(attributes, 'dir', config.dir);
    attributes = setAttribute(attributes, 'data-locale', code);
    return `<html${attributes}>`;
  });
  html = html.replace(/<title>[^<]*<\/title>/, () => `<title>${escapeHtml(seo.title)}</title>`);

  const translatedElements = [...html.matchAll(/\bdata-i18n="([^"]+)"/g)].length;
  let replacements = 0;
  html = html.replace(/<([a-z][\w:-]*)\b([^<>]*\sdata-i18n="([^"]+)"[^<>]*)>([^<>]*)<\/\1>/gi,
    (_, tag, attributes, key) => {
      replacements += 1;
      return `<${tag}${attributes}>${escapeHtml(translation(code, key))}</${tag}>`;
    });
  assert.equal(replacements, translatedElements, 'Every data-i18n element must contain only text, never child markup.');

  html = html.replace(/<([a-z][\w:-]*)\b([^<>]*)>/gi, (_, tag, attributes) => {
    for (const [dataName, name] of [['title', 'title'], ['aria', 'aria-label'], ['placeholder', 'placeholder'], ['alt', 'alt']]) {
      const key = attributes.match(new RegExp(`\\sdata-i18n-${dataName}="([^"]+)"`))?.[1];
      if (key) attributes = setAttribute(attributes, name, translation(code, key));
    }
    return `<${tag}${attributes}>`;
  });

  html = html.replace(/<select\b([^>]*\bdata-language-select\b[^>]*)>([\s\S]*?)<\/select>/g,
    (_, attributes, options) => `<select${attributes}>${options.replace(/<option\b([^>]*)>/g, (_option, optionAttributes) => {
      const clean = optionAttributes.replace(/\sselected(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+))?/g, '');
      return `<option${clean}${clean.match(/\bvalue="([^"]+)"/)?.[1] === code ? ' selected' : ''}>`;
    })}</select>`);

  const links = Object.entries(LOCALES).map(([target, locale]) =>
    `<a href="${relativeLocaleUrl(code, target)}" lang="${locale.tag}" hreflang="${locale.hreflang}"${target === code ? ' aria-current="page"' : ''}>${escapeHtml(locale.label)}</a>`).join('\n          ');
  assert.ok(html.includes('<!-- LANGUAGE_LINKS -->'), 'The template must expose crawlable language links.');
  html = html.replaceAll('<!-- LANGUAGE_LINKS -->',
    `<nav class="language-links" aria-label="${escapeHtml(translation(code, 'header.language'))}">\n          ${links}\n        </nav>`);

  const alternateLinks = Object.entries(LOCALES).map(([target, locale]) =>
    `<link rel="alternate" hreflang="${locale.hreflang}" href="${canonicalUrl(target)}">`);
  alternateLinks.push(`<link rel="alternate" hreflang="x-default" href="${BASE_URL}">`);
  html = html.replace(/^\s*<link rel="alternate" hreflang="[^"]+"[^>]*>\s*$/gm, '');
  assert.match(html, /<link rel="canonical"[^>]*>/);
  html = html.replace(/<link rel="canonical"[^>]*>/, () =>
    `<link rel="canonical" href="${url}">\n  ${alternateLinks.join('\n  ')}`);

  for (const [attribute, name, content] of [
    ['name', 'description', seo.description],
    ['property', 'og:title', seo.ogTitle],
    ['property', 'og:description', seo.ogDescription],
    ['property', 'og:url', url],
    ['property', 'og:locale', config.og],
    ['name', 'twitter:title', seo.ogTitle],
    ['name', 'twitter:description', seo.ogDescription],
    ['property', 'og:image:alt', seo.imageAlt ?? translation(code, 'hero.imageAlt')],
    ['name', 'twitter:image:alt', seo.imageAlt ?? translation(code, 'hero.imageAlt')]
  ]) html = setMeta(html, attribute, name, content);

  html = html.replace(/^\s*<meta property="og:locale:alternate"[^>]*>\s*$/gm, '');
  const alternateLocales = Object.entries(LOCALES).filter(([target]) => target !== code)
    .map(([, locale]) => `<meta property="og:locale:alternate" content="${locale.og}">`);
  html = html.replace(/<meta property="og:locale"[^>]*>/, (tag) => `${tag}\n  ${alternateLocales.join('\n  ')}`);

  let hasStructuredData = false;
  html = html.replace(/(<script\b[^>]*\bid="structuredData"[^>]*>)([\s\S]*?)(<\/script>)/,
    (_, opening, json, closing) => {
      hasStructuredData = true;
      const data = JSON.parse(json);
      const app = data['@graph']?.find((item) => item['@type'] === 'WebApplication');
      const site = data['@graph']?.find((item) => item['@type'] === 'WebSite');
      assert.ok(app && site, 'The template must describe the website and the application.');
      for (const item of [app, site]) {
        item.url = url;
        item.inLanguage = config.tag;
        item.name = seo.ogTitle;
        item.description = seo.description;
      }
      app.featureList = [
        ['metric.temperature', 'metric.humidity', 'metric.battery'],
        ['settings.sync', 'settings.autoClock'],
        ['settings.timeFormat', 'settings.unit'],
        ['history.export'],
        ['devices.title', 'connection.autoRetry']
      ].map((keys) => keys.map((key) => translation(code, key)).join(', '));
      const serialized = JSON.stringify(data, null, 2).replace(/</g, '\\u003c');
      return `${opening}\n${serialized}\n  ${closing}`;
    });
  assert.ok(hasStructuredData, 'Missing structured data in the template.');

  if (code !== 'en') {
    html = html.replace(/\b(src|href)="((?:img\/[^"<>]+)|(?:styles\.css|i18n\.js|app\.js|site\.webmanifest)(?:[?#][^"<>]*)?)"/g,
      (_, attribute, value) => `${attribute}="../${value}"`);
  }
  return html.replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

function renderSitemap() {
  const alternates = Object.entries(LOCALES).map(([code, locale]) =>
    `    <xhtml:link rel="alternate" hreflang="${locale.hreflang}" href="${canonicalUrl(code)}"/>`);
  alternates.push(`    <xhtml:link rel="alternate" hreflang="x-default" href="${BASE_URL}"/>`);
  const urls = Object.keys(LOCALES).map((code) => [
    '  <url>',
    `    <loc>${canonicalUrl(code)}</loc>`,
    `    <lastmod>${CONTENT_MODIFIED}</lastmod>`,
    ...alternates,
    ...['img/og-dashboard.jpg', 'img/lywsd02-product.webp', 'img/dashboard_lywsd02.jpg'].map((image) =>
      `    <image:image><image:loc>${new URL(image, BASE_URL).href}</image:loc></image:image>`),
    '  </url>'
  ].join('\n'));
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/build-locales.cjs. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml"',
    '        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">',
    ...urls,
    '</urlset>',
    ''
  ].join('\n');
}

function buildFiles() {
  const template = fs.readFileSync(path.join(ROOT, 'templates/index.html'), 'utf8');
  const files = new Map(Object.keys(LOCALES).map((code) => [
    code === 'en' ? 'index.html' : `${code}/index.html`, renderPage(template, code)
  ]));
  files.set('sitemap.xml', renderSitemap());
  return files;
}

function main(args) {
  assert.ok(args.length === 0 || (args.length === 1 && args[0] === '--check'), 'Usage: node scripts/build-locales.cjs [--check]');
  const check = args.includes('--check');
  const stale = [];
  const files = buildFiles();
  for (const [relative, content] of files) {
    const filename = path.join(ROOT, relative);
    if (check) {
      if (!fs.existsSync(filename) || fs.readFileSync(filename, 'utf8') !== content) stale.push(relative);
    } else {
      fs.mkdirSync(path.dirname(filename), { recursive: true });
      fs.writeFileSync(filename, content);
    }
  }
  if (stale.length) {
    console.error(`Generated files are stale: ${stale.join(', ')}. Run node scripts/build-locales.cjs.`);
    process.exitCode = 1;
  } else {
    console.log(`${check ? 'Checked' : 'Generated'} ${files.size - 1} language pages and sitemap.xml.`);
  }
}

module.exports = { buildFiles, renderPage, renderSitemap };
if (require.main === module) main(process.argv.slice(2));
